// Live oracle: v3 structure generation against the real model (goal item 1 +
// falsification bar "Struct or enum generation modifies bytes outside the
// target symbol's span"). A struct header+doc and an enum header+doc are
// generated by qwen3-coder:30b through the SAME service pipeline the command
// uses (kind-routed prompt, type-aware extraction), spliced into a fixture at
// the exact span, and the boundary invariant is asserted through the oracle AND
// an independent UTF-8 comparison. Skip with SKIP_LIVE=1.
//
// Run: node --test --test-concurrency=1 test/impl-v3-structgen-live.test.cjs

const test = require("node:test");
const assert = require("node:assert");
const { bundleCore } = require("./.blind-util.cjs");

const SKIP = process.env.SKIP_LIVE === "1" ? "SKIP_LIVE=1" : false;
const LIVE_TIMEOUT = 120_000;
const API_BASE = "http://localhost:11434";
const MODEL = "qwen3-coder:30b";

const { mod, cleanup } = bundleCore(
  "impl-v3-structgen-live",
  `export { FnGenService } from "../src/core/fnGenService";
export { spliceSpan, byteCompareOutsideSpan } from "../src/core/span";
export { listModels } from "../src/core/ollama";\n`
);
const { FnGenService, spliceSpan, byteCompareOutsideSpan, listModels } = mod;
test.after(cleanup);

const LIVE_CONFIG = {
  apiBase: API_BASE,
  model: MODEL,
  fallbackModel: "qwen2.5-coder:14b-instruct-q4_K_M",
  maxTokens: 512,
  temperature: 0.2,
  numGpu: 30,
};

// A struct target mid-file so both boundary regions are non-empty. The doc
// comment (outside the span) carries the semantics; the header carries little.
const STRUCT_SRC = `//! Fixture module for the v3 structure-gen boundary bar.

pub fn double(x: i64) -> i64 {
    x * 2
}

/// Connection settings for a TCP server.
///
/// Carries the bind address, the port to listen on, and whether TLS is on.
pub struct ServerConfig {
}

pub fn triple(x: i64) -> i64 {
    x * 3
}
`;

const ENUM_SRC = `//! Fixture module for the v3 structure-gen boundary bar.

pub fn double(x: i64) -> i64 {
    x * 2
}

/// A message on the wire: a request carrying a payload, a response carrying a
/// status code, or a heartbeat that carries nothing.
pub enum WireMessage {
}

pub fn triple(x: i64) -> i64 {
    x * 3
}
`;

function spanOf(src, headNeedle) {
  const start = src.indexOf(headNeedle);
  const end = src.indexOf("}", start) + 1;
  return { start, end };
}

function assertOutsideByteIdentical(original, result, span) {
  const prefix = original.slice(0, span.start);
  const suffix = original.slice(span.end);
  assert.strictEqual(result.slice(0, span.start), prefix, "independent: prefix region unchanged");
  assert.strictEqual(result.slice(result.length - suffix.length), suffix, "independent: suffix region unchanged");
  assert.ok(Buffer.from(result.slice(0, span.start)).equals(Buffer.from(prefix)), "independent: prefix bytes identical (UTF-8)");
  assert.ok(Buffer.from(result.slice(result.length - suffix.length)).equals(Buffer.from(suffix)), "independent: suffix bytes identical (UTF-8)");
}

test("precondition: live ollama is up and the model is pulled", { skip: SKIP, timeout: LIVE_TIMEOUT }, async () => {
  const tags = await listModels(API_BASE);
  assert.ok(Array.isArray(tags), "server reachable");
  assert.ok(tags.includes(MODEL), `${MODEL} must be pulled; got ${JSON.stringify(tags)}`);
});

async function roundTrip(t, { src, kind, signature, docComment, headNeedle, name, memberSubstring }) {
  const span = spanOf(src, headNeedle);
  const lines = [];
  const svc = new FnGenService(LIVE_CONFIG, undefined, (l) => lines.push(l));
  try {
    const out = await svc.generate({ signature, docComment, languageId: "rust", span, kind });
    assert.ok(out, "live generation resolves a result");
    assert.ok(out.text.length > 0, "non-empty postprocessed text");
    assert.strictEqual(out.model, MODEL);
    assert.ok(out.text.includes(name), `the ${kind} names ${name}; got:\n${out.text}`);
    assert.ok(/\{[\s\S]*\}/.test(out.text), `the ${kind} carries a brace body; got:\n${out.text}`);

    const spliced = spliceSpan(src, span, out.text);
    assert.strictEqual(spliced, src.slice(0, span.start) + out.text + src.slice(span.end));
    assert.strictEqual(byteCompareOutsideSpan(src, spliced, span), true, "oracle: outside the span byte-identical");
    assertOutsideByteIdentical(src, spliced, span);
    // The neighbouring functions and the doc comment survived.
    assert.ok(spliced.includes("pub fn double(x: i64) -> i64 {"), "function above intact");
    assert.ok(spliced.includes("pub fn triple(x: i64) -> i64 {"), "function below intact");
    assert.ok(spliced.includes(docComment.split("\n")[0]), "doc comment (outside span) intact");
    t.diagnostic(`${kind} ${name} generated ${out.text.length} chars; boundary held. ${memberSubstring ? "note: " + memberSubstring : ""}`);
    return out.text;
  } finally {
    svc.dispose();
  }
}

test("boundary bar: live STRUCT round trip, splice lands in the span, bytes outside byte-identical", { skip: SKIP, timeout: LIVE_TIMEOUT }, async (t) => {
  await roundTrip(t, {
    src: STRUCT_SRC, kind: "struct",
    signature: "pub struct ServerConfig", name: "ServerConfig",
    docComment: "/// Connection settings for a TCP server.\n///\n/// Carries the bind address, the port to listen on, and whether TLS is on.",
    headNeedle: "pub struct ServerConfig",
  });
});

test("boundary bar: live ENUM round trip, splice lands in the span, bytes outside byte-identical", { skip: SKIP, timeout: LIVE_TIMEOUT }, async (t) => {
  await roundTrip(t, {
    src: ENUM_SRC, kind: "enum",
    signature: "pub enum WireMessage", name: "WireMessage",
    docComment: "/// A message on the wire: a request carrying a payload, a response carrying a\n/// status code, or a heartbeat that carries nothing.",
    headNeedle: "pub enum WireMessage",
  });
});
