// session-v44 phase 4: the cache, measured END TO END through the product on a
// real Claude subscription. Not a unit test and not a shim - a real extension
// host, a real pinned context block, two real generations of DIFFERENT
// functions, and the product's own channel read back.
//
// This is the only place the session's central claim can be checked. Every
// tier below it proves the transport does what the contract says against a fake
// CLI; none of them can tell you that the real CLI actually reads the fork's
// context out of cache. Two rounds is the minimum that can: the first builds
// the checkpoint, the second is the one that either reads it or does not.
//
// IT SPENDS REAL SUBSCRIPTION QUOTA. Three CLI calls (turn 1, two generations)
// plus the harness context each carries. Gated on C80_CLAUDE_LIVE=1 so a normal
// `npm run test:vscode` never bills anyone by accident.
//
// Run:
//   C80_CLAUDE_LIVE=1 DISPLAY=:1 npx vscode-test --config test-vscode/.vscode-test.mjs --label ts
//
// What each assertion needed a live round for:
//   - that `--resume <id> --fork-session` still forks on the installed CLI
//   - that a fork of a DIFFERENT function reads the whole block set from cache
//   - the actual before/after in the product's own billed-equivalent units

'use strict';

const assert = require('assert');
const vscode = require('vscode');
const fs = require('fs');
const os = require('os');
const path = require('path');

const LIVE = process.env.C80_CLAUDE_LIVE === '1';
const LIVE_MODEL = process.env.C80_CLAUDE_MODEL || 'claude-sonnet-4-5';
const EXT_ID = 'utilitydelta.column-80';

// Same instrument as v33 and v43: the channel tee is read out of the
// environment when the extension ACTIVATES, so both facts are captured at
// module load. A missing instrument read as a measurement is the failure this
// comment exists to stop.
const extensionAtLoad = vscode.extensions.getExtension(EXT_ID);
const ACTIVE_AT_LOAD = extensionAtLoad ? extensionAtLoad.isActive === true : false;
const LOG_FROM_ENV = typeof process.env.C80_LOG_FILE === 'string' && process.env.C80_LOG_FILE !== '';
const DEFAULT_LOG = path.join(os.tmpdir(), `c80-v44-live-${process.pid}.log`);
if (!LOG_FROM_ENV) {
  process.env.C80_LOG_FILE = DEFAULT_LOG;
}
const LOG_FILE = process.env.C80_LOG_FILE;
const NO_INSTRUMENT = !LOG_FROM_ENV && ACTIVE_AT_LOAD;

const logMark = () => {
  try {
    return fs.statSync(LOG_FILE).size;
  } catch {
    return 0;
  }
};
const logSince = (mark) => {
  try {
    return fs.readFileSync(LOG_FILE).subarray(mark).toString('utf8');
  } catch {
    return '';
  }
};
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

const roundLine = (text) => /^\[claude-code\] fence-strip=.*$/m.exec(text);
const turn1Line = (text) => /^\[claude-code\] turn1=.*$/m.exec(text);
const field = (line, name) => {
  const m = new RegExp(`(?:^| )${name}=([^ ]*)`).exec(line);
  return m === null ? undefined : m[1];
};

// The pinned block. It has to clear MIN_PREFIX_BYTES (2048) by a wide margin,
// because the point of the measurement is a block set big enough to be worth
// caching, which is what a real reference file looks like.
const REF_REL = 'playground/c80_v44_reference.ts';
const REF_TEXT =
  '// Column 80 session-v44 reference material. Pinned as a context block by the test.\n' +
  Array.from(
    { length: 60 },
    (_, i) =>
      `/** Formats measurement row ${i} for the report. */\n` +
      `export function formatRow${i}(label: string, value: number): string {\n` +
      `  return \`\${label.padEnd(24)} \${value.toFixed(2)}\`;\n` +
      `}\n`
  ).join('\n');

const TARGET_REL = 'playground/c80_v44_target.ts';
// TWO functions, generated one after the other against the SAME pinned block.
// Different targets is the whole point: an identical prompt would hit the CLI's
// own end-of-turn breakpoint and prove nothing about the fork.
const TARGET_TEXT = `// Column 80 session-v44 live target. Regenerated by the test; safe to delete.

/** Returns the label padded to 24 characters, as formatRow0 does. */
export function v44PadLabel(label: string): string {
  return '';
}

/** Returns the value with exactly two decimal places, as formatRow0 does. */
export function v44FormatValue(value: number): string {
  return '';
}
`;

suite('session-v44: the cache, measured through the product', () => {
  let repo;
  let refUri;
  let targetUri;
  let priorModel;

  suiteSetup(async function () {
    if (!LIVE) {
      return;
    }
    this.timeout(120000);
    const folders = vscode.workspace.workspaceFolders;
    assert.ok(folders && folders.length > 0, 'the tier must run rooted at a workspace folder');
    repo = folders[0].uri.fsPath;

    refUri = vscode.Uri.file(path.join(repo, REF_REL));
    targetUri = vscode.Uri.file(path.join(repo, TARGET_REL));
    fs.mkdirSync(path.dirname(refUri.fsPath), { recursive: true });
    fs.writeFileSync(refUri.fsPath, REF_TEXT);
    fs.writeFileSync(targetUri.fsPath, TARGET_TEXT);

    const cfg = vscode.workspace.getConfiguration('column80');
    priorModel = cfg.inspect('fnGenModel')?.globalValue;
    await cfg.update('fnGenProvider', 'claude-code', vscode.ConfigurationTarget.Global);
    await cfg.update('fnGenModel', LIVE_MODEL, vscode.ConfigurationTarget.Global);

    const ext = vscode.extensions.getExtension(EXT_ID);
    assert.ok(ext, 'the extension must be present in the host');
    await ext.activate();
    await sleep(3000);

    // Pin the reference file the way a human does, through the real command.
    await vscode.commands.executeCommand('column80.contextClear');
    await vscode.commands.executeCommand('column80.contextAddFile', refUri, [refUri]);
    await sleep(500);
  });

  suiteTeardown(async () => {
    if (!LIVE) {
      return;
    }
    const cfg = vscode.workspace.getConfiguration('column80');
    await cfg.update('fnGenProvider', undefined, vscode.ConfigurationTarget.Global);
    // vscode-test keeps its user-data-dir between runs, so a setting left here
    // is a setting the NEXT run inherits. That is how v43's first version came
    // to pass once and then fail.
    await cfg.update('fnGenModel', priorModel, vscode.ConfigurationTarget.Global);
    try {
      await vscode.commands.executeCommand('column80.contextClear');
      fs.rmSync(refUri.fsPath, { force: true });
      fs.rmSync(targetUri.fsPath, { force: true });
    } catch {
      /* every artifact here is disposable by construction */
    }
  });

  // Drives one generation inside the named function and returns the round line
  // plus everything the channel said, so a failure prints the evidence rather
  // than a bare timeout.
  //
  // Anchored on the FUNCTION NAME and then the first body line after it. Both
  // targets have byte-identical bodies on purpose (they are both stubs), so an
  // anchor on the body text finds the first one twice and the second
  // generation silently regenerates the first.
  async function generateAt(fnName, budgetMs) {
    // Clear anything the previous generation left on screen, with the gesture a
    // human would use. A preview still open over the target is the difference
    // between the second round generating the function asked for and the second
    // round never being asked at all.
    try {
      await vscode.commands.executeCommand('column80.proposalReject');
    } catch {
      /* nothing staged is the normal case for the first round */
    }
    const doc = await vscode.workspace.openTextDocument(targetUri);
    const editor = await vscode.window.showTextDocument(doc, { preview: false });
    const source = doc.getText();
    const head = source.indexOf(`export function ${fnName}`);
    assert.ok(head > 0, `the target ${fnName} must be findable`);
    const idx = source.indexOf("return", head);
    assert.ok(idx > head, `the body of ${fnName} must be findable`);
    editor.selection = new vscode.Selection(doc.positionAt(idx), doc.positionAt(idx));

    const mark = logMark();
    // Fire and watch the channel rather than awaiting: a failed round ends on an
    // AWAITED error toast whose promise never settles until someone dismisses
    // it (the trap recorded in .vscode-test.mjs).
    void vscode.commands.executeCommand('column80.generateFunction');

    const deadline = Date.now() + budgetMs;
    let round;
    while (Date.now() < deadline) {
      round = roundLine(logSince(mark));
      if (round) {
        break;
      }
      await sleep(1000);
    }
    const text = logSince(mark);
    assert.ok(round, `no [claude-code] round line within the budget. Channel said:\n${text.slice(0, 4000)}`);
    return { round: round[0], turn1: turn1Line(text)?.[0], text };
  }

  test('generation 1 WARMS the checkpoint: turn 1 runs, and the round forks off it', async function () {
    if (!LIVE) {
      this.skip();
    }
    if (NO_INSTRUMENT) {
      assert.fail('no channel instrument: set C80_LOG_FILE before the host starts');
    }
    // Two CLI calls plus a cold start.
    this.timeout(420000);

    const { round, turn1, text } = await generateAt("v44PadLabel", 400000);
    console.log(`[v44 evidence] ${turn1 ?? '<no turn1 line>'}`);
    console.log(`[v44 evidence] ${round}`);
    assert.ok(!/round=failed/.test(round), `the live round FAILED: ${round}\nchannel:\n${text.slice(0, 4000)}`);

    assert.ok(turn1, `turn 1 must get its own evidence line so its cost is visible:\n${text.slice(0, 4000)}`);
    assert.strictEqual(
      field(round, 'cache-mode'),
      'warmed',
      `the first generation against a cold block set builds the checkpoint and forks off it: ${round}`
    );
  });

  test('generation 2 of a DIFFERENT function FORKS, and reads the block set from cache', async function () {
    if (!LIVE) {
      this.skip();
    }
    if (NO_INSTRUMENT) {
      assert.fail('no channel instrument: set C80_LOG_FILE before the host starts');
    }
    this.timeout(420000);

    const { round, turn1, text } = await generateAt("v44FormatValue", 400000);
    console.log(`[v44 evidence] ${round}`);
    assert.ok(!/round=failed/.test(round), `the live round FAILED: ${round}\nchannel:\n${text.slice(0, 4000)}`);

    assert.strictEqual(
      turn1,
      undefined,
      `the checkpoint is already warm, so turn 1 must NOT run again: ${turn1}`
    );
    assert.strictEqual(
      field(round, 'cache-mode'),
      'forked',
      `a second generation against the same blocks forks the live checkpoint: ${round}`
    );

    // The claim the whole session rests on, in the provider's own numbers: a
    // DIFFERENT function, forked from the same checkpoint, reads the context
    // rather than re-writing it.
    const cread = Number(field(round, 'cread'));
    const cwrite = Number(field(round, 'cwrite'));
    assert.ok(
      Number.isFinite(cread) && Number.isFinite(cwrite),
      `the round must report real cache accounting, not ? or absent: ${round}`
    );
    assert.ok(cread > 0, `a forked round reads the checkpoint from cache: ${round}`);
    assert.ok(
      cwrite < cread,
      `the fork must write far less than it reads, or the checkpoint bought nothing: ${round}`
    );
    console.log(`[v44 measurement] forked round: cwrite=${cwrite} cread=${cread} billed-eq=${field(round, 'billed-eq')}`);
  });
});
